version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        # command: python manage.py runserver 0.0.0.0:8000
        container_name: drp-flask
        volumes:
            - .:/usr/src/app
        # env_file:
        #     - ./.env.dev
        ports:
            - "3001:3001"
